### ISSUE TITLE
Write newly discovered terms into dictionary

### ISSUE THREAD

**Issue by jakebeal** [TASBE/SBOL-Sample-Creator#13]
If the user has samples that use things not in the dictionary, then it should ask if they want to add it to the dictionary, and do so if they say yes, rather than refusing to proceed.

**Comment by jakebeal** [comment]
You should be able to make use of this library: https://github.com/SD2E/sbol-dictionary-writer

**Comment by dashaveraksa** [comment]
Completed, although it doesn't seem to be generating the SynBioHub URI.

**Comment by dashaveraksa** [comment]
Never mind it just took some time, all is good now.
