### ISSUE TITLE
Ground components with terms in SynBioHub

### ISSUE THREAD

**Issue by jakebeal** [TASBE/SBOL-Sample-Creator#4]
Rather than only creating new components as the "leaf" ComponentDefinitions of our sample, we should give a way to ground them with existing component definitions in SynBioHub.

**Comment by jakebeal** [comment]
We're doing this via the LCP Dictionary.

**Comment by dashaveraksa** [comment]
Completed. Only caveat is that it doesn't inform the user to go create a dictionary entry if something in their sample (like FlpO) is not there already, instead it creates a new ComponentDef. This will be fixed when we get the API working without uploading the client key.

**Comment by jakebeal** [comment]
Can you open an issue to track the incomplete portion, and link it back to here?
